# Generated by Django 5.2.7 on 2025-11-01 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_meeting_ticket_delete_supportticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='start_time',
        ),
    ]
