# Generated by Django 5.2.7 on 2025-11-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_remove_meeting_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_link',
        ),
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('stopped', 'Stopped')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('completed', 'Completed')], default='waiting', max_length=20),
        ),
    ]
