# Generated by Django 5.2.7 on 2025-11-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_remove_meeting_meeting_link_meeting_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='endTime',
            field=models.DateTimeField(default="2025-11-02T12:00:00"),
        ),
    ]
