# Generated by Django 5.2.7 on 2025-11-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_meeting_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='endTime',
            field=models.DateTimeField(default='01/02/03'),
        ),
    ]
