# Generated by Django 5.2.7 on 2025-11-01 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_meeting_endtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='endTime',
        ),
    ]
