# Generated by Django 5.2.7 on 2025-11-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_remove_meeting_endtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_link',
            field=models.CharField(default='google.com'),
        ),
    ]
