# Generated by Django 5.2.7 on 2025-11-01 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_meeting_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='endTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_link',
            field=models.CharField(default='https://google.com', max_length=255),
        ),
    ]
