# Generated by Django 5.2.7 on 2025-11-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_meeting_endtime_meeting_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
