# Generated by Django 5.2.7 on 2025-11-01 14:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_meeting_endtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_link',
        ),
        migrations.AddField(
            model_name='meeting',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(auto_now=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('joined', 'Joined'), ('completed', 'Completed')], default='waiting', max_length=20),
        ),
    ]
