# Generated by Django 5.2.7 on 2025-11-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_remove_meeting_endtime_remove_meeting_meeting_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='date',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='start_time',
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_link',
            field=models.CharField(default='google.com', max_length=300),
        ),
    ]
